dependencies:
# https://hub.kubeapps.com/charts/stable/nginx-ingress
- name: nginx-ingress
  version: "1.6.17"
  repository: "@stable"
# https://hub.kubeapps.com/charts/stable/postgresql
- name: postgresql
  version: "5.3.8"
  repository: "@stable"