email: your@email.here

# TODO: make functionally different environments
environment: production

weatherUnlockedAppId: your-secret-here
weatherUnlockedAppKey: your-secret-here
openWeatherMapAppId: your-secret-here

image:
  profile: mrasap

backend:
  replicaCount: 1

  image:
    repo: powderbooking-backend
    tag: latest
    pullPolicy: Always

  ingress:
    enabled: true
    paths:
      - /
    # TODO: register DNS
    hosts:
      - api.powderbooking.com

  # TODO: add resources
  resources: {}

frontend:
  replicaCount: 1

  image:
    repo: powderbooking-frontend
    tag: latest
    pullPolicy: Always

  ingress:
    enabled: true
    paths:
      - /
    # TODO: register DNS
    hosts:
      - powderbooking.com

  # TODO: add resources
  resources: {}

scraper:
  image:
    repo: powderbooking-scraper
    tag: latest
    pullPolicy: Always

  restartPolicy: Never

  weather:
    # At minute 1 past every 6th hour
    schedule: '1 */6 * * *'

  forecast:
    # At 01:01 on every day-of-month
    schedule: '1 1 */1 * *'


nginx-ingress:
  controller:
    resources:
      requests:
        cpu: 100m
        memory: 64Mi
  defaultfrontend:
    resources:
      limits:
        cpu: 10m
        memory: 20Mi
      requests:
        cpu: 10m
        memory: 20Mi

postgresql:
  resources:
    requests:
      memory: 256Mi
      cpu: 250m

  postgresqlUsername: powderbooking
  postgresqlPassword: a-super-secret-password
  postgresqlDatabase: powderbooking
