{{- if .Values.frontend.ingress.enabled -}}
{{/*These variables are required because we are referencing to them within a range function,
    which would change the scope*/}}
{{- $ingressPaths := .Values.backend.ingress.paths -}}
{{- $name := printf "%s-%s" .Release.Name "backend" -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-backend
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}-backend
    app.kubernetes.io/component: backend
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/part-of: {{ .Chart.Name }}
    app.kubernetes.io/version: {{ .Values.backend.image.tag }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ .Chart.Name }}
  annotations:
    kubernetes.io/ingress.class: nginx
    certmanager.k8s.io/cluster-issuer: letsencrypt-issuer
spec:
  tls:
    - hosts:
      {{- range .Values.backend.ingress.hosts }}
        - {{ . | quote }}
      {{- end }}
      secretName: {{ .Release.Name }}-backend
  rules:
  {{- range .Values.backend.ingress.hosts }}
    - host: {{ . | quote }}
      http:
        paths:
	{{- range $ingressPaths }}
          - path: {{ . }}
            backend:
              serviceName: {{ $name }}
              servicePort: 80
	{{- end }}
  {{- end }}
{{- end }}
