apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-scraper-secret
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}-scraper-secret
    app.kubernetes.io/component: secret
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/part-of: {{ .Chart.Name }}
    app.kubernetes.io/version: {{ .Chart.Version }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ .Chart.Name }}
type: Opaque
data:
  WEATHERUNLOCKED_APP_ID: {{ .Values.weatherUnlockedAppId | b64enc | quote }}
  WEATHERUNLOCKED_APP_KEY: {{ .Values.weatherUnlockedAppKey | b64enc | quote }}
  OPENWEATHERMAP_APP_ID: {{ .Values.openWeatherMapAppId | b64enc | quote }}