apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ .Release.Name }}-scraper-forecast
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}-scraper-forecast
    app.kubernetes.io/component: scraper-forecast
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/part-of: {{ .Chart.Name }}
    app.kubernetes.io/version: {{ .Chart.Version }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ .Chart.Name }}
spec:
  schedule: {{ .Values.scraper.forecast.schedule | quote }}
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: scraper
              image: {{ .Values.image.profile }}/{{ .Values.scraper.image.repo }}:{{ .Values.scraper.image.tag }}
              imagePullPolicy: {{ .Values.scraper.image.pullPolicy }}
              env:
{{ include "env.project" . | indent 16 }}
{{ include "env.postgresql" . | indent 16 }}
{{ include "env.scraper" . | indent 16 }}
              command: ["python3"]
              args: ["app.py", "forecast"]
          restartPolicy: {{ .Values.scraper.restartPolicy }}